### ISSUE TITLE
Code reformating is non-functional in latte templates

### ISSUE THREAD

**Issue by iguana007** [JanTvrdik/intellij-latte#12]
If I want to use reformat code in the latte template, it is not working at all (nothing happens when shortcut "Ctrl+Alt+L" is triggered).
Temporary solution was in my case disabling of this plugin and assignment of Smarty file type to *.latte files - but it would be nice, if support for this would be enabled within this plugin too.

**Comment by simPod** [comment]
It was working for me with PHPStorm 9. Not working in 10 though

**Comment by matej21** [comment]
fixed
