### ISSUE TITLE
Feature proposal: syntax highlight n-macros

### ISSUE THREAD

**Issue by Mikulas** [JanTvrdik/intellij-latte#13]
Arguably there might be user set macro attributes, but handling the n prefix would cover almost all (if not all) uses.

The `n:if` argument could be highlighted same as the macro argument:

![screenshot 2014-12-10 10 21 49](https://cloud.githubusercontent.com/assets/192200/5373468/5fdf9abe-8056-11e4-97c8-949fcf5a11a3.png)

**Comment by matej21** [comment]
fixed 4bf3391be5
