### ISSUE TITLE
Suppress missing tag {/block} warning

### ISSUE THREAD

**Issue by EdaCZ** [JanTvrdik/intellij-latte#16]
First of all thanks for great improvements of this plugin, it's awesome! :-)

But still, there is one small thing that I am not comfortable with. I don't use closing tag {/block} in presenters latte templates, because it's optional. But plugin is showing error "Tag is not closed". Would it be possible to suppress this error for last block macro in template?

**Comment by matej21** [comment]
Are you sure you are using Latte and not Smarty plugin (check Settings/Editor/File types)? this error should not happen in this plugin :)

**Comment by fprochazka** [comment]
It's definitely working for me with actuall latte from repository and 
![snimek obrazovky porizeny 2016-03-17 14 02 40](https://cloud.githubusercontent.com/assets/158625/13846641/edb9a9b0-ec48-11e5-8f51-15042b255a1a.png)

**Comment by EdaCZ** [comment]
@matej21 You are right :-) 

Self note: next time sync work & home PhpStorm settings first.

Sorry. Closing.
