### ISSUE TITLE
Edit title for collapsed block

### ISSUE THREAD

**Issue by Trejjam** [JanTvrdik/intellij-latte#19]
Hi, it is possible edit title for collapsed block?

For example:
It is impossible recognize name of collapsed block 
![snimek z 2016-03-26 20-08-58](https://cloud.githubusercontent.com/assets/3594540/14061967/fee4970c-f38e-11e5-872d-4be1885fb8d6.png)

![snimek z 2016-03-26 20-09-19](https://cloud.githubusercontent.com/assets/3594540/14061968/020bda44-f38f-11e5-97da-91c74045e1cf.png)

Something like show class in HTML tag would be nice

**Comment by matej21** [comment]
Fixed 7d6b51d55

**Comment by Trejjam** [comment]
Thank you
Dne 2. 4. 2016 7:51 odpoledne napsal uživatel "David Matějka" <
notifications@github.com>:
