### ISSUE TITLE
Code reformating removes comment blocks

### ISSUE THREAD

**Issue by contineo-cz** [JanTvrdik/intellij-latte#20]
Hi, when reformat code (Code/Reformat Code), comments change to empty space:
```
<div>
{*
  my comment
*}
</div>
```
changed to:
```
<div>



</div>
```
Feature or error?

**Comment by matej21** [comment]
Seems like a bug to me, but I'm unable to reproduce it :(

**Comment by salatos** [comment]
Hi, if it is help you somehow, it also happens when I cut and paste comments, move commented line (Move statement - ctrl shift up/down), or just paste whatever into empty comment.

**Comment by DanielNoga** [comment]
Code in first comment does not trigger the bug for me, but this code lower, it triggers:

```
<div class="container">
		{input password, class => "form-control", placeholder => "Heslo"}
			{*
			<div id="remember" class="checkbox">
				<label>
					<input type="checkbox" value="remember-me"> Remember me
				</label>
			</div>
			*}
		{input submit_login, class => "btn btn-lg btn-primary btn-block btn-signin"}
</div>
```
