### ISSUE TITLE
Unknow macro php

### ISSUE THREAD

**Issue by Studioartcz** [JanTvrdik/intellij-latte#28]
Hi,
what about unpair "php" macro? Storm alerting that is unknow. Thanks

**Comment by matej21** [comment]
Do you have latest version? It is there since 0.3.2 https://github.com/JanTvrdik/intellij-latte/commit/9baa4e07b39e227d2d315f664b83ecc1801ba6dd

**Comment by Studioartcz** [comment]
Oh, 0.3.1.
Why plugin doesn't update automatically?

**Comment by matej21** [comment]
It does, phpstorm offers you an update, you just have to confirm that.
